# Generated by Django 3.0.2 on 2020-01-23 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('naveena', '0003_auto_20200123_1520'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='naveena',
            options={},
        ),
        migrations.AlterModelManagers(
            name='naveena',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='naveena',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='naveena',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='naveena',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='naveena',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='naveena',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='naveena',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='naveena',
            name='password',
        ),
        migrations.RemoveField(
            model_name='naveena',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='naveena',
            name='username',
        ),
    ]
